project:
  type: website
  output-dir: docs

website:
  title: "SLURM User Guide"
  page-navigation: true
  navbar:
    left:
      - text: "Quick Start"
        href: content/quick-start/index.qmd
      - text: "Guide"
        href: content/guide/index.qmd
  sidebar:
    - id: quick-start
      title: "Quick Start"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - content/get-started/index.qmd
    - id: guide
      collapse-level: 2
      title: "Guide"
      style: "floating"
      align: left
      contents:
        - section: "Guide"
          href: content/guide/index.qmd
          contents:
            - section: "Module System"
              href: content/guide/index.qmd
            - section: "Containers"
              href: content/guide/index.qmd              
            - section: "Spack"
              href: content/spack/index.qmd
              contents:
                - text: "Setup"
                  href: content/spack/spack-setup.qmd
                - text: "Install Packages"
                  href: content/spack/spack-install-packages.qmd
            - section: "JupyterLab"
              href: content/guide/index.qmd
            - section: "RStudio"
              href: content/guide/index.qmd
            - section: "VSCode Remote"
              href: content/guide/index.qmd            
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


execute:
  echo: true
  eval: true
  freeze: auto
  cache: true

